name: Shell
on:
  push:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  Shell:
    container:
      image: ubuntu:bionic
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Shell_HT
      run: |
        set -e
        apt-get update -y
        sleep 10
